#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys
import getopt
from models.player import exception as pException
from core.command import exception as CommandException
import core.Rpg
from argparse import ArgumentParser


def main(argv):
	parser = ArgumentParser()

	parser.add_argument(
		"-d", "--debug",
		dest="debug", help="Enable debug mode", action="store_true"
	)
	parser.add_argument(
		"-j", "--json",
		dest="json", help="Output data in JSON", action="store_true"
	)
	parser.add_argument(
		"-l", "--login",
		dest="login", help="Player login", metavar="LOGIN"
	)
	parser.add_argument(
		"-p", "--password",
		dest="password", help="Player password", metavar="PASSWORD"
	)
	parser.add_argument(
		"-w", "--world",
		dest="world", help="World to load", metavar="WORLD"
	)
	parser.add_argument(
		"action",
		metavar="A", nargs='*', help="Action to execute"
	)

	args = parser.parse_args()

	render = core.Rpg.RENDER_TEXT
	if args.json is not False:
		render = core.Rpg.RENDER_JSON

	isInteractive = args.action == []
	rpg = core.Rpg.Rpg(args.debug, render, isInteractive)

	world = '' if args.world is None else str(args.world)
	login = None
	password = None
	if args.login is not None:
		login = args.login
	if args.password is not None:
		password = args.password

	try:
		rpg.init(world, login, password, args.action)
	except KeyboardInterrupt:
		print("")
		return
	except BaseException as e:
		print(rpg.renderException(e))
		return

	rpg.run()


if __name__ == "__main__":
	main(sys.argv[1:])
