#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys
import getopt
from models.player import exception as pException
from core.command import exception as CommandException
import CLI.main
import core
from argparse import ArgumentParser


def main(argv):
	parser = ArgumentParser()

	parser.add_argument(
		"-d", "--debug",
		dest="debug", help="Enable debug mode", action="store_true"
	)
	parser.add_argument(
		"-j", "--json",
		dest="json", help="Output data in JSON", action="store_true"
	)
	parser.add_argument(
		"-l", "--login",
		dest="login", help="Player login", metavar="LOGIN"
	)
	parser.add_argument(
		"-w", "--world",
		dest="world", help="World to load", metavar="WORLD"
	)

	args = parser.parse_args()

	render = core.Rpg.RENDER_TEXT
	if args.json is not False:
		render = core.Rpg.RENDER_JSON

	world = '' if args.world is None else str(args.world)

	login = None
	if args.login is not None:
		login = args.login

	CLI.main.main(args.debug, world, login)

if __name__ == "__main__":
	main(sys.argv[1:])
